INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('RelaisDeDemarreur', 1, '2019-03-18 15:22:12', '2019-03-18 15:22:00', null, 'onférences', 'http://url.fr', true, 'Lyon', 'modich', '50e', 'Bien utet rebase • Delicious Insight', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('BoitierCdi', 2, '2019-03-18 15:30:59', '2019-03-18 15:30:59', null, '

Référence OEM : 5D7E13110000. Fourni avec piston complet, joints haut et bas ', 'http://pougsfd.fr', true, 'Lyon', 'modich', '50e', 'Cylindre 1Tek origine fonte Yamaha X-Max 125/MBK Cityliner 125 2007-13', '1902');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('BouchonDeRadiateur', 3, '2019-03-18 15:30:59', '2019-03-18 15:30:59', null, '

Ligne complète Scorpion Serket avec silencieux en titane pour Yamaha MT-07. ', 'http://pougsfd.fr', true, 'Nancy', 'MT-07', '70e', 'Ligne Complète Scorpion Serket Silencieux Titane Yamaha MT-07', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('RelaisDeDemarreur', 11, '2019-03-18 15:34:46', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'titre annonce', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('RelaisDeDemarreur', 12, '2019-03-18 16:24:50', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'tessfdg fgjfgk ghjgfhke', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('CarenageDivers', 13, '2019-03-19 10:53:01', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'Carénage divers Entity CATEGORY', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('BequilleLaterale', 14, '2019-03-19 10:54:46', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'Béquille latérale CATEGORY', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('Guidon', 15, '2019-03-19 10:55:07', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'Guidon CATEGORY', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('Guidon', 16, '2019-03-19 10:56:16', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'Guidon CATEGORYsubclass', '2019');
INSERT INTO motobox.ad (category, id, created_at, updated_at, brand, description, image_url, is_active, location, model, price, title, year) VALUES ('Guidon', 17, '2019-03-19 10:58:07', null, 'le brand ouaich', 'desc annonce', 'http://url.fr', true, 'Lyon', 'model de tes morts', '50e', 'Levier de frein subclass', '2019');